dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_kmp_llvm
  - _pytorch_select=0.2=gpu_0
  - blas=1.0=mkl
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2024.6.2=hbcca054_0
  - cairo=1.16.0=hb05425b_5
  - certifi=2021.5.30=py36h5fab9bb_0
  - cffi=1.14.6=py36h400218f_0
  - cloudpickle=2.0.0=pyhd3eb1b0_0
  - colorama=0.4.4=pyhd3eb1b0_0
  - cudatoolkit=11.7.0=hd8887f6_10
  - cudnn=8.2.1.32=h86fa8c9_0
  - cycler=0.11.0=pyhd3eb1b0_0
  - cytoolz=0.11.0=py36h7b6447c_0
  - dask-core=2021.3.0=pyhd3eb1b0_0
  - dataclasses=0.8=pyh787bdff_2
  - dbus=1.13.18=hb2f20db_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - expat=2.6.2=h6a678d5_0
  - ffmpeg=4.0.2=ha0c5888_2
  - fontconfig=2.14.1=h52c9d5c_1
  - freeglut=3.4.0=h6a678d5_0
  - freetype=2.12.1=h4a9f257_0
  - future=0.18.2=py36h5fab9bb_3
  - glib=2.69.1=h4ff587b_1
  - gmp=6.1.2=hf484d3e_1000
  - gnutls=3.5.19=h2a4e5f8_1
  - graphite2=1.3.14=h295c915_1
  - gst-plugins-base=1.14.1=h6a678d5_1
  - gstreamer=1.14.1=h5eee18b_1
  - harfbuzz=1.8.8=hffaf4a1_0
  - hdf5=1.10.2=hba1933b_1
  - icu=58.2=he6710b0_3
  - imageio=2.9.0=pyhd3eb1b0_0
  - intel-openmp=2022.1.0=h9e868ea_3769
  - jasper=2.0.14=hd8c5072_2
  - jpeg=9e=h5eee18b_1
  - kiwisolver=1.3.1=py36h2531618_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.38=h1181459_1
  - lerc=3.0=h295c915_0
  - libblas=3.9.0=8_mkl
  - libdeflate=1.17=h5eee18b_1
  - libffi=3.3=he6710b0_2
  - libgcc-ng=13.2.0=h77fa898_13
  - libgfortran-ng=7.5.0=ha8ba4b0_17
  - libgfortran4=7.5.0=ha8ba4b0_17
  - libglu=9.0.0=hf484d3e_1
  - libgomp=13.2.0=h77fa898_13
  - libiconv=1.17=hd590300_2
  - liblapack=3.9.0=8_mkl
  - libopencv=3.4.2=hb342d67_1
  - libopus=1.3.1=h7b6447c_0
  - libpng=1.6.39=h5eee18b_0
  - libprotobuf=3.15.8=h780b84a_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtiff=4.5.1=h6a678d5_0
  - libuuid=1.41.5=h5eee18b_0
  - libvpx=1.7.0=h439df22_0
  - libwebp-base=1.3.2=h5eee18b_0
  - libxcb=1.15=h7f8727e_0
  - libxml2=2.9.14=h74e7548_0
  - llvm-openmp=12.0.1=h4bd325d_1
  - lz4-c=1.9.4=h6a678d5_1
  - magma=2.5.4=h6103c52_2
  - matplotlib=3.3.4=py36h06a4308_0
  - matplotlib-base=3.3.4=py36h62a2d02_0
  - mkl=2020.4=h726a3e6_304
  - mkl-service=2.3.0=py36he8ac12f_0
  - mkl_fft=1.3.0=py36h54f3939_0
  - mkl_random=1.1.1=py36h0573a6f_0
  - nccl=2.12.12.1=h0800d71_0
  - ncurses=6.4=h6a678d5_0
  - nettle=3.3=0
  - networkx=2.5=py_0
  - ninja=1.10.2=h06a4308_5
  - ninja-base=1.10.2=hd09550d_5
  - numpy=1.19.2=py36h54aff64_0
  - numpy-base=1.19.2=py36hfa32c7d_0
  - olefile=0.46=py36_0
  - opencv=3.4.2=py36h6fd60c2_1
  - openh264=1.8.0=hdbcaa40_1000
  - openjpeg=2.4.0=h3ad879b_0
  - openssl=1.1.1w=hd590300_0
  - pcre=8.45=h295c915_0
  - pillow=8.3.1=py36h2c7a002_0
  - pip=21.2.2=py36h06a4308_0
  - pixman=0.40.0=h7f8727e_1
  - py-opencv=3.4.2=py36hb342d67_1
  - pycparser=2.21=pyhd3eb1b0_0
  - pyparsing=3.0.4=pyhd3eb1b0_0
  - pyqt=5.9.2=py36h05f1152_2
  - python=3.6.13=h12debd9_1
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - python_abi=3.6=2_cp36m
  - pytorch=1.8.0=cuda112py36h5fea6e2_1
  - pytorch-gpu=1.8.0=cuda112py36h0bbbad9_1
  - pywavelets=1.1.1=py36h7b6447c_2
  - pyyaml=5.4.1=py36h27cfd23_1
  - qt=5.9.7=h5867ecd_1
  - readline=8.2=h5eee18b_0
  - regex=2021.8.3=py36h7f8727e_0
  - scipy=1.5.2=py36h0b6359f_0
  - sip=4.19.8=py36hf484d3e_0
  - sleef=3.5.1=h9b69904_2
  - sqlite=3.45.3=h5eee18b_0
  - tk=8.6.14=h39e8969_0
  - toolz=0.11.2=pyhd3eb1b0_0
  - tornado=6.1=py36h27cfd23_0
  - tqdm=4.63.0=pyhd3eb1b0_0
  - wheel=0.37.1=pyhd3eb1b0_0
  - x264=1!152.20180806=h14c3975_0
  - xz=5.4.6=h5eee18b_1
  - yaml=0.2.5=h7b6447c_0
  - zlib=1.2.13=h5eee18b_1
  - zstd=1.5.5=hc292b87_2
  - pip:
    - absl-py==0.15.0
    - appdirs==1.4.4
    - astor==0.8.1
    - astunparse==1.6.3
    - cached-property==1.5.2
    - cachetools==4.2.4
    - charset-normalizer==2.0.12
    - clang==5.0
    - einops==0.4.1
    - filelock==3.4.1
    - flatbuffers==1.12
    - gast==0.3.3
    - google-auth==1.35.0
    - google-auth-oauthlib==0.4.6
    - google-pasta==0.2.0
    - grpcio==1.32.0
    - h5py==2.10.0
    - huggingface-hub==0.4.0
    - idna==3.7
    - importlib-metadata==4.8.3
    - importlib-resources==5.4.0
    - keras==2.2.4
    - keras-applications==1.0.8
    - keras-preprocessing==1.1.2
    - lmdb==1.5.1
    - lpips==0.1.4
    - markdown==3.3.7
    - oauthlib==3.2.2
    - opt-einsum==3.3.0
    - packaging==21.3
    - pandas==1.1.5
    - pooch==1.6.0
    - protobuf==4.21.0
    - pyasn1==0.5.1
    - pyasn1-modules==0.3.0
    - pydeprecate==0.3.2
    - python-version==0.0.2
    - pytz==2024.2
    - requests==2.27.1
    - requests-oauthlib==2.0.0
    - rsa==4.9
    - scikit-image==0.17.1
    - setuptools==59.6.0
    - six==1.15.0
    - tensorboard==2.10.1
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.1
    - tensorboardx==2.6.2
    - tensorflow==1.9.0
    - tensorflow-estimator==2.4.0
    - tensorflow-gpu==2.4.0
    - termcolor==1.1.0
    - tf-slim==1.1.0
    - tifffile==2020.9.3
    - timm==0.6.12
    - torch==1.8.1+cu101
    - torchaudio==0.8.1
    - torchmetrics==0.8.2
    - torchvision==0.9.1+cu101
    - typing-extensions==3.7.4.3
    - urllib3==1.26.19
    - werkzeug==2.0.3
    - wrapt==1.12.1
    - zipp==3.6.0


